### PR TITLE
Fix parsing custom fields

### PR DESCRIPTION
**Pull request by epic-alex-rodionov**

### CODE REVIEW

**Comment by Crim** [comment]
So while this fixes the parsing issue, it also is a breaking change to the API (returning an Object instead of a String).

In general breaking backwards compatibility of the API I'm OK with, but I'd prefer if we do, we make a change that in some form maintains type safety.  Unless I'm misunderstanding, an example usage of this would now look something like:

```java
Object fieldAValue = prospect.getCustomField("fieldA");
if (fieldAValue instanceOf String) {
 String fieldAStr = (String) fieldAValue;
} else if (fieldAValue instanceOf Map) {
 Map fieldAMap = (Map) fieldAValue;
}
```

I wonder if we could instead encapsulate the value in some kind of `CustomFieldValue` object that could have an API like:

```java
class CustomFieldValue {
  boolean isAString();
  String getValueAsString();

  boolean isABoolean();
  Boolean getValueAsBoolean();

  boolean isAnInteger()
  Integer getValueAsInteger();

  boolean isRecordMultiple();
  List<CustomFieldValue> getRecordMultipleValues()

  // etc...
}

CustomFieldValue fieldAValue = prospect.getCustomField("fieldA");
fieldAValue.getAsString();
```

Granted, it's not exactly an ideal API either, but at least maintains some form of type safety and doesn't force the end user into writing a bunch of instanceOf checks.

Another possible alternative would be for the library to make an API call behind the scenes to retrieve and cache the datatypes of custom fields and be able to more intelligently deserialize the values into more concrete types.  I'm also not entirely sure what that would look like in reality.

Open to other ideas as well? Thoughts?

**Comment by epic-alex-rodionov** [comment]
Well, `CustomFieldValue` will be more breaking change to the API, because it breaks current users implementation. Object does not break it.  Also Object allows users do what they want with response data.
We can split this change on 2 steps: 
1. Object.
2. CustomFieldValue in needed.

**Comment by Crim** [comment]
Hmm not sure that's accurate, as assigning an Object to a String would be a compilation error.

image

Perhaps there's a good middle ground.  What if we changed the type of the map in Prospect.java as you have in your PR so parsing doesn't explode.

```java
    // Custom fields
    private Map<String, Object> customFields = new HashMap<>();
```

Keep the existing `getCustomFieldValue()` unchanged in definition, but only have it return String values, and add a new method to get multi-select fields?  Maybe something like

```java
    /**
     * Utility method to get custom field value.
     *
     * @param customFieldName Field to retrieve value for.
     * @return Value of the custom field.
     */
    public String getCustomField(final String customFieldName) {
        final Object value = customFields.get(customFieldName);
        if (value instanceof String) {
            return (String) value;
        } else {
            throw some kind of exception instructing to use the new method to access select multiple?
        }
    }
    
   // new method to get multi select values?
    public Map<String, String> getCustomFieldValues(final String customFieldName) {
        ....
    }
```

**Comment by epic-alex-rodionov** [comment]
As a variant just return string value, but also create additional method which will return a map:
```
    public String getCustomField(final String customFieldName) {
        return String.valueOf(customFields.get(customFieldName));
    }

    public Map<String, String> getCustomFields(final String customFieldName) {
        return (Map<String, String>) customFields.get(customFieldName);
    }
```

**Comment by epic-alex-rodionov** [comment]
@Crim can it be merged/released?

**Comment by Crim** [comment]
Yep, looks good, thanks!  I'll get this merged here shortly.

**Comment by epic-alex-rodionov** [comment]
@Crim when it will be released? Will it have version 1.1.3?

**Comment by Crim** [comment]
Yea, likely 1.2.0.  I'm just running through a few test cases to make sure I understand how it works.

Reading a prospect with a multi-select field seems to be parsing incorrectly.

In the app:
image

XML returned by the API:
image

Parsed Prospect only showing a single value stored:
image

**Comment by Crim** [comment]
It seems like it is parsing the below as a map instead of a list of values.

```xml
<customFieldName>
  <value>value1</value>
  <value>value1</value>
  <value>value1</value>
</customFieldName>
```

gets converted to `LinkedHashMap<String, String>` where the key is always `value`, so each entry overwrites the previous one

**Comment by epic-alex-rodionov** [comment]
Looks like jackson cannot determine this properly

**Comment by epic-alex-rodionov** [comment]
@Crim should this new issue be fixed now or it can be done in the next release? For me the most important to fix issue: `Cannot deserialize instance of java.lang.String out of START_OBJECT`..

**Pull request merged**
